import { formatNumber, getCooldown, formatTime, getRandom, styleText } from '../lib/utils.js';

const JOBS = [
    'trabajaste en una panaderia',
    'repariste pizza',
    'hiciste un pastel',
    'vendiste carbón',
    'le serviste un café a un cliente',
    'diseñaste un logo para una empresa',
    'escribiste un documental de animales',
    'tocaste musica con una guitarra',
    'cortaste el cesped del jardin de tu vecina',
    'reparaste electrodomésticos',
    'creaste un phonk',
    'reparaste un ventilador',
    'arreglaste una radio',
    'creaste una aplicación para android',
    'hiciste una cirujia a una señora',
    'le contaste una vulnerabilidad a Google',
    'creaste un sistema operativo',
    'limpiaste ventanas de un edificio',
    'paseaste perros en el parque',
    'entregaste paquetes por la ciudad',
    'preparaste hamburguesas en un restaurante',
    'vendiste flores en la esquina',
    'pintaste una casa completa',
    'reparaste una computadora',
    'enseñaste matemáticas a un estudiante',
    'fotografiaste una boda',
    'escribiste un artículo para un blog',
    'editaste videos para YouTube',
    'diseñaste una página web',
    'tradujiste documentos al inglés',
    'organizaste un evento corporativo',
    'limpiaste piscinas',
    'instalaste aire acondicionado',
    'reparaste un coche',
    'vendiste seguros de vida',
    'atendiste en una farmacia',
    'preparaste sushi en un restaurante',
    'bartender en un bar nocturno',
    'diste clases de yoga',
    'cortaste el cabello en una peluquería',
    'maquillaste a una novia',
    'reparaste celulares',
    'vendiste ropa en una tienda',
    'limpiaste oficinas por la noche',
    'cuidaste niños por la tarde',
    'cocinaste en un food truck',
    'hiciste tatuajes en un estudio',
    'arreglaste bicicletas',
    'vendiste helados en la playa',
    'instalaste cámaras de seguridad',
    'reparaste laptops',
    'diste clases de guitarra',
    'pintaste murales en paredes',
    'editaste fotos para clientes',
    'grabaste un podcast',
    'hiciste animaciones 3D',
    'desarrollaste un videojuego',
    'moderaste un servidor de Discord',
    'escribiste código para una startup',
    'hiciste pruebas de software',
    'diseñaste un cartel publicitario',
    'grabaste voces para comerciales',
    'compusiste música para un videojuego',
    'reparaste instrumentos musicales',
    'vendiste artesanías',
    'hiciste joyería personalizada',
    'reparaste relojes antiguos',
    'restauraste muebles viejos',
    'tapizaste un sofá',
    'instalaste pisos de madera',
    'arreglaste tuberías',
    'instalaste paneles solares',
    'limpiaste alfombras',
    'fumigaste una casa',
    'podaste árboles',
    'diseñaste jardines',
    'vendiste plantas',
    'cuidaste mascotas',
    'bañaste perros',
    'entrenaste caballos',
    'trabajaste en un zoológico',
    'limpiaste acuarios',
    'vendiste comida para mascotas',
    'atendiste en una veterinaria',
    'rescataste animales abandonados',
    'diste clases de natación',
    'fuiste salvavidas en una piscina',
    'entrenaste en un gimnasio',
    'diste masajes terapéuticos',
    'hiciste manicura y pedicura',
    'depilaste cejas',
    'aplicaste tratamientos faciales',
    'vendiste productos de belleza',
    'trabajaste como modelo fotográfico',
    'desfilaste en una pasarela',
    'actuaste en un comercial',
    'doblaste voces para series',
    'hiciste stand-up comedy',
    'cantaste en un bar',
    'bailaste en un espectáculo',
    'hiciste malabares en la calle',
    'pintaste caricaturas',
    'leíste cartas del tarot',
    'hiciste trucos de magia',
    'fuiste mimo por unas horas',
    'vendiste periódicos',
    'repartiste publicidad',
    'pusiste carteles en postes',
    'hiciste encuestas telefónicas',
    'trabajaste en atención al cliente',
    'respondiste emails corporativos',
    'organizaste archivos digitales',
    'transcribiste audios',
    'subtitulaste videos',
    'corregiste ortografía de textos',
    'escribiste artículos SEO',
    'gestionaste redes sociales',
    'creaste contenido para TikTok',
    'editaste reels de Instagram',
    'diseñaste historias de Instagram',
    'hiciste thumbnails para videos',
    'escribiste descripciones de productos',
    'moderaste comentarios en redes',
    'respondiste mensajes de clientes',
    'hiciste servicio de chat en vivo',
    'vendiste por teléfono',
    'hiciste telemarketing',
    'agendaste citas médicas',
    'confirmaste reservas de hotel',
    'atendiste en recepción',
    'limpiaste habitaciones de hotel',
    'serviste desayunos en un hotel',
    'trabajaste como botones',
    'fuiste guía turístico',
    'vendiste tours',
    'manejaste un taxi',
    'condujiste un uber',
    'repartiste comida en moto',
    'trabajaste en delivery',
    'empacaste productos',
    'etiquetaste cajas',
    'cargaste camiones',
    'descargaste mercancía',
    'organizaste inventario',
    'contaste productos en bodega',
    'operaste montacargas',
    'trabajaste en logística',
    'empacaste regalos',
    'armaste muebles',
    'instalaste estanterías',
    'colgaste cuadros',
    'instalaste cortinas',
    'reparaste persianas',
    'cambiaste cerraduras',
    'duplicaste llaves',
    'afilaste cuchillos',
    'reparaste paraguas',
    'cosiste ropa',
    'arreglaste dobladillos',
    'bordaste nombres en camisas',
    'tejiste bufandas',
    'hiciste colchas a mano',
    'vendiste artículos tejidos',
    'hiciste zapatos a medida',
    'reparaste calzado',
    'limpiaste zapatos',
    'vendiste accesorios',
    'hiciste pulseras artesanales',
    'vendiste collares',
    'reparaste joyas',
    'puliste metales',
    'grabaste nombres en metal',
    'hiciste trofeos personalizados',
    'imprimiste camisetas',
    'diseñaste stickers',
    'imprimiste tarjetas de presentación',
    'encuadernaste libros',
    'plastificaste documentos',
    'fotocopiaste papeles',
    'escaneaste archivos',
    'digitalizaste documentos viejos',
    'organizaste papeles de oficina',
    'archivaste expedientes',
    'revisaste contratos',
    'redactaste cartas formales',
    'hiciste presentaciones en PowerPoint',
    'creaste hojas de cálculo',
    'analizaste datos en Excel',
    'hiciste reportes financieros',
    'llevaste contabilidad básica',
    'calculaste impuestos',
    'llenaste declaraciones',
    'asesoraste sobre finanzas',
    'vendiste criptomonedas',
    'hiciste trading de acciones',
    'asesoraste inversiones',
    'gestionaste carteras de inversión',
    'vendiste bienes raíces',
    'mostraste casas a clientes',
    'tomaste fotos de propiedades',
    'hiciste tours virtuales de casas',
    'valuaste propiedades',
    'redactaste contratos de renta',
    'negociaste precios',
    'cerraste una venta importante',
    'conseguiste un cliente nuevo',
    'hiciste networking',
    'asististe a una conferencia',
    'diste una charla motivacional',
    'capacitaste empleados',
    'hiciste onboarding de personal',
    'reclutaste candidatos',
    'hiciste entrevistas de trabajo',
    'revisaste currículums',
    'evaluaste desempeño laboral',
    'mediaste un conflicto laboral',
    'organizaste un team building',
    'planificaste un retiro corporativo',
    'reservaste vuelos para ejecutivos',
    'coordinaste videoconferencias',
    'preparaste salas de reuniones',
    'serviste café en juntas',
    'tomaste notas en una reunión',
    'redactaste minutas',
    'enviaste reportes semanales',
    'actualizaste bases de datos',
    'limpiaste listas de contactos',
    'verificaste información de clientes',
    'hiciste llamadas de seguimiento',
    'cobraste facturas vencidas',
    'enviaste recordatorios de pago',
    'procesaste pagos',
    'emitiste facturas',
    'reconciliaste cuentas bancarias',
    'auditaste gastos',
    'redujiste costos operativos',
    'negociaste con proveedores',
    'compraste suministros de oficina',
    'gestionaste compras',
    'comparaste precios',
    'buscaste mejores ofertas',
    'negociaste descuentos',
    'ahorraste dinero a la empresa',
    'optimizaste procesos',
    'implementaste mejoras',
    'documentaste procedimientos',
    'creaste manuales de usuario',
    'escribiste tutoriales',
    'grabaste videos educativos',
    'diste soporte técnico',
    'resolviste problemas de IT',
    'instalaste software',
    'actualizaste sistemas',
    'configuraste redes',
    'instalaste routers',
    'reparaste conexiones de internet',
    'solucionaste problemas WiFi',
    'recuperaste datos perdidos',
    'hiciste backups de información',
    'migraste datos a la nube',
    'configuraste servidores',
    'administraste bases de datos',
    'optimizaste consultas SQL',
    'hiciste deploy de aplicaciones',
    'configuraste pipelines CI/CD',
    'escribiste tests unitarios',
    'debugeaste código',
    'revisaste pull requests',
    'documentaste APIs',
    'creaste diagramas de flujo',
    'diseñaste arquitectura de software',
    'hiciste refactoring de código',
    'optimizaste performance',
    'redujiste tiempos de carga',
    'mejoraste la experiencia de usuario',
    'hiciste pruebas A/B',
    'analizaste métricas de usuarios',
    'interpretaste datos de analytics',
    'creaste dashboards',
    'visualizaste datos',
    'hiciste reportes automáticos',
    'programaste tareas automáticas',
    'creaste bots de automatización',
    'integraste APIs externas',
    'configuraste webhooks',
    'implementaste autenticación',
    'mejoraste la seguridad',
    'parchaste vulnerabilidades',
    'hiciste pentesting',
    'auditaste seguridad',
    'configuraste firewalls',
    'bloqueaste ataques',
    'monitoreaste servidores',
    'respondiste a incidentes',
    'restauraste servicios caídos',
    'hiciste mantenimiento preventivo',
    'actualizaste dependencias',
    'parcheaste sistemas',
    'solucionaste bugs críticos',
    'implementaste hotfixes',
    'desplegaste actualizaciones',
    'monitoreaste logs',
    'investigaste errores',
    'optimizaste queries',
    'mejoraste índices de base de datos',
    'limpiaste datos duplicados',
    'normalizaste bases de datos',
    'migraste a nueva arquitectura',
    'escalaste servidores',
    'configuraste load balancers',
    'implementaste caché',
    'optimizaste imágenes',
    'comprimiste archivos',
    'minificaste código',
    'implementaste CDN',
    'mejoraste SEO',
    'optimizaste meta tags',
    'creaste sitemaps',
    'enviaste sitio a Google',
    'mejoraste posicionamiento',
    'escribiste contenido optimizado',
    'investigaste palabras clave',
    'analizaste competencia',
    'creaste estrategia de contenido',
    'planificaste calendario editorial',
    'escribiste posts de blog',
    'creaste infografías',
    'diseñaste ebooks',
    'escribiste whitepapers',
    'creaste case studies',
    'redactaste testimonios',
    'editaste contenido web',
    'revisaste gramática',
    'mejoraste redacción',
    'adaptaste tono de voz',
    'localizaste contenido',
    'tradujiste sitios web',
    'adaptaste contenido cultural',
    'escribiste copys publicitarios',
    'creaste slogans',
    'nombraste productos',
    'escribiste scripts de video',
    'redactaste guiones',
    'escribiste diálogos',
    'creaste personajes',
    'desarrollaste historias',
    'escribiste novelas cortas',
    'redactaste poemas',
    'escribiste letras de canciones',
    'compusiste melodías',
    'produjiste beats',
    'mezclaste canciones',
    'masterizaste audio',
    'grabaste voces',
    'editaste podcasts',
    'quitaste ruido de audios',
    'sincronizaste audio con video',
    'agregaste subtítulos',
    'tradujiste subtítulos',
    'editaste transcripciones',
    'creaste closed captions',
    'hiciste descripciones de audio',
    'adaptaste contenido para accesibilidad',
    'probaste accesibilidad web',
    'implementaste ARIA labels',
    'mejoraste contraste de colores',
    'optimizaste para lectores de pantalla',
    'creaste versiones móviles',
    'diseñaste interfaces responsive',
    'probaste en múltiples dispositivos',
    'solucionaste bugs de CSS',
    'arreglaste problemas de layout',
    'implementaste animaciones',
    'creaste transiciones suaves',
    'diseñaste microinteracciones',
    'mejoraste feedback visual',
    'implementaste estados de carga',
    'creaste skeletons de carga',
    'optimizaste lazy loading',
    'implementaste infinite scroll',
    'creaste paginación',
    'diseñaste filtros de búsqueda',
    'implementaste autocompletado',
    'creaste sugerencias de búsqueda',
    'mejoraste algoritmos de búsqueda',
    'implementaste búsqueda fuzzy',
    'indexaste contenido',
    'optimizaste búsqueda full-text',
    'implementaste faceted search',
    'creaste filtros avanzados',
    'diseñaste ordenamiento',
    'implementaste favoritos',
    'creaste listas de deseos',
    'diseñaste carritos de compra',
    'implementaste checkout',
    'integraste pasarelas de pago',
    'configuraste Stripe',
    'implementaste PayPal',
    'agregaste métodos de pago',
    'configuraste envíos',
    'calculaste costos de envío',
    'implementaste seguimiento de paquetes',
    'creaste notificaciones de pedidos',
    'enviaste emails transaccionales',
    'diseñaste templates de email',
    'implementaste newsletters',
    'creaste campañas de email',
    'segmentaste audiencias',
    'personalizaste mensajes',
    'hiciste email marketing',
    'analizaste tasas de apertura',
    'optimizaste subject lines',
    'mejoraste CTR',
    'implementaste A/B testing',
    'analizaste resultados',
    'tomaste decisiones basadas en datos',
    'creaste experimentos',
    'validaste hipótesis',
    'iteraste sobre diseños',
    'mejoraste conversiones',
    'optimizaste funnels',
    'redujiste fricción',
    'simplificaste procesos',
    'eliminaste pasos innecesarios',
    'mejoraste onboarding',
    'creaste tutoriales interactivos',
    'diseñaste tours guiados',
    'implementaste tooltips',
    'agregaste ayuda contextual',
    'creaste centro de ayuda',
    'escribiste FAQs',
    'organizaste documentación',
    'creaste base de conocimiento',
    'implementaste búsqueda en docs',
    'versionaste documentación',
    'mantuviste docs actualizados',
    'revisaste documentación obsoleta',
    'actualizaste screenshots',
    'grabaste videos tutoriales',
    'creaste GIFs explicativos',
    'diseñaste diagramas',
    'ilustraste conceptos',
    'simplificaste explicaciones',
    'clarificaste instrucciones',
    'mejoraste ejemplos',
    'agregaste casos de uso',
    'documentaste mejores prácticas',
    'escribiste guías de estilo',
    'estableciste estándares',
    'creaste plantillas',
    'diseñaste componentes reusables',
    'construiste design systems',
    'documentaste componentes',
    'creaste storybook',
    'mantuviste consistencia visual',
    'estableciste guías de marca',
    'creaste brand guidelines',
    'diseñaste paletas de colores',
    'seleccionaste tipografías',
    'creaste sistemas de espaciado',
    'definiste breakpoints',
    'estableciste grid systems',
    'diseñaste layouts',
    'creaste wireframes',
    'diseñaste mockups',
    'hiciste prototipos',
    'creaste prototipos interactivos',
    'validaste diseños con usuarios',
    'hiciste pruebas de usabilidad',
    'realizaste entrevistas',
    'observaste usuarios',
    'analizaste comportamiento',
    'identificaste pain points',
    'mapeaste customer journeys',
    'creaste user personas',
    'investigaste usuarios',
    'hiciste research cualitativo',
    'realizaste encuestas',
    'analizaste feedback',
    'sintetizaste insights',
    'presentaste hallazgos',
    'comunicaste recomendaciones',
    'priorizaste mejoras',
    'creaste roadmaps',
    'planificaste sprints',
    'estimaste esfuerzos',
    'asignaste tareas',
    'gestionaste proyectos',
    'facilitaste ceremonias ágiles',
    'moderaste retrospectivas',
    'organizaste dailies',
    'planificaste sprints',
    'refinaste backlog',
    'priorizaste features',
    'negociaste alcance',
    'gestionaste stakeholders',
    'comunicaste progreso',
    'reportaste bloqueos',
    'escalaste problemas',
    'coordinaste equipos',
    'alineaste objetivos',
    'celebraste logros',
    'reconociste esfuerzos',
    'motivaste al equipo',
    'resolviste conflictos',
    'mediaste desacuerdos',
    'facilitaste consensos',
    'tomaste decisiones difíciles',
    'asumiste responsabilidad',
    'diste feedback constructivo',
    'mentoreaste juniors',
    'compartiste conocimiento',
    'enseñaste buenas prácticas',
    'hiciste pair programming',
    'revisaste código con juniors',
    'explicaste conceptos complejos',
    'respondiste preguntas',
    'ayudaste a depurar',
    'guiaste en arquitectura',
    'compartiste recursos',
    'recomendaste libros',
    'sugeriste cursos',
    'organizaste workshops',
    'diste charlas internas',
    'compartiste aprendizajes',
    'documentaste lecciones',
    'creaste guías de troubleshooting',
    'escribiste postmortems',
    'analizaste incidentes',
    'implementaste mejoras',
    'preveniste futuros problemas',
    'reforzaste monitoreo',
    'mejoraste alertas',
    'configuraste notificaciones',
    'automatizaste respuestas',
    'creaste runbooks',
    'documentaste procedimientos de emergencia',
    'entrenaste para crisis',
    'practicaste disaster recovery',
    'probaste backups',
    'validaste restauraciones',
    'aseguraste business continuity',
    'minimizaste downtime',
    'mejoraste reliability',
    'aumentaste uptime',
    'redujiste latencia',
    'optimizaste throughput',
    'escalaste horizontalmente',
    'implementaste sharding',
    'distribuiste carga',
    'balanceaste tráfico',
    'implementaste failover',
    'configuraste alta disponibilidad',
    'diseñaste para resiliencia',
    'implementaste circuit breakers',
    'manejaste errores gracefully',
    'implementaste retries',
    'configuraste timeouts',
    'optimizaste recursos',
    'redujiste costos de cloud',
    'rightsizaste instancias',
    'implementaste auto-scaling',
    'optimizaste uso de memoria',
    'redujiste CPU usage',
    'mejoraste eficiencia',
    'implementaste green computing',
    'redujiste huella de carbono',
    'optimizaste consumo energético',
    'implementaste mejores prácticas sustentables',
    'promoviste trabajo remoto',
    'facilitaste colaboración distribuida',
    'configuraste herramientas remotas',
    'mejoraste comunicación asíncrona',
    'documentaste todo claramente',
    'creaste cultura de documentación',
    'promoviste transparencia',
    'compartiste información abiertamente',
    'mantuviste equipo informado',
    'comunicaste cambios',
    'notificaste updates',
    'escribiste changelogs',
    'mantuviste release notes',
    'versionaste cambios',
    'seguiste semantic versioning',
    'gestionaste deprecations',
    'migraste usuarios',
    'mantuviste retrocompatibilidad',
    'soportaste versiones antiguas',
    'graduaste features beta',
    'experimentaste con nuevas ideas',
    'validaste concepts',
    'construiste MVPs',
    'lanzaste features',
    'monitoreaste adopción',
    'recolectaste feedback',
    'iteraste rápidamente',
    'pivoteaste cuando fue necesario',
    'aprendiste de fracasos',
    'celebraste pequeñas victorias',
    'mantuviste momentum',
    'persististe ante desafíos',
    'superaste obstáculos',
    'encontraste soluciones creativas',
    'pensaste fuera de la caja',
    'innovaste en tu campo',
    'propusiste nuevas ideas',
    'desafiaste el status quo',
    'cuestionaste supuestos',
    'buscaste mejores formas',
    'optimizaste constantemente',
    'nunca dejaste de aprender',
    'te mantuviste actualizado',
    'leíste documentación técnica',
    'experimentaste con tecnologías',
    'construiste side projects',
    'contribuiste a open source',
    'reportaste bugs',
    'enviaste pull requests',
    'mejoraste proyectos públicos',
    'ayudaste a la comunidad',
    'respondiste en foros',
    'ayudaste en Stack Overflow',
    'escribiste en Medium',
    'compartiste en Twitter',
    'creaste contenido técnico',
    'grabaste screencasts',
    'streaming de código',
    'enseñaste en vivo',
    'respondiste preguntas en vivo',
    'construiste en público',
    'compartiste tu proceso',
    'inspiraste a otros',
    'mentoreaste remotamente',
    'ofreciste ayuda gratuita',
    'devolviste a la comunidad',
    'promoviste diversidad en tech',
    'apoyaste a minorías',
    'creaste espacios inclusivos',
    'combatiste discriminación',
    'promoviste equidad',
    'abogaste por cambios',
    'alzaste tu voz',
    'defendiste lo correcto',
    'actuaste con integridad',
    'mantuviste ética profesional',
    'respetaste privacidad',
    'protegiste datos de usuarios',
    'implementaste privacidad by design',
    'minimizaste recolección de datos',
    'anonimizaste información',
    'encriptaste datos sensibles',
    'cumpliste con GDPR',
    'respetaste CCPA',
    'mantuviste compliance',
    'documentaste políticas',
    'comunicaste términos claramente',
    'obtuviste consentimiento',
    'respetaste decisiones de usuarios',
    'implementaste controles',
    'diste opciones de privacidad',
    'permitiste exportar datos',
    'facilitaste portabilidad',
    'implementaste derecho al olvido',
    'borraste datos a petición',
    'respetaste solicitudes de usuarios',
    'atendiste reclamos',
    'resolviste disputas',
    'compensaste errores',
    'pediste disculpas cuando fue necesario',
    'asumiste errores',
    'corregiste problemas',
    'mejoraste continuamente',
    'escuchaste feedback',
    'valoraste opiniones',
    'implementaste sugerencias',
    'co-creaste con usuarios',
    'involucraste a la comunidad',
    'construiste en colaboración',
    'fomentaste participación',
    'creaste sentido de pertenencia',
    'construiste comunidad',
    'moderaste discusiones',
    'facilitaste conversaciones',
    'conectaste personas',
    'hiciste networking efectivo',
    'construiste relaciones',
    'mantuviste contactos',
    'seguiste con leads',
    'nutriste relaciones',
    'agregaste valor constantemente',
    'ayudaste sin esperar nada',
    'compartiste generosamente',
    'conectaste oportunidades',
    'hiciste introducciones',
    'recomendaste personas',
    'escribiste referencias',
    'avlaste por talento',
    'reclutaste activamente',
    'identificaste talento',
    'evaluaste candidatos',
    'condujiste entrevistas técnicas',
    'evaluaste skills',
    'verificaste referencias',
    'negociaste ofertas',
    'cerraste contrataciones',
    'onboardeaste nuevos empleados',
    'integraste al equipo',
    'asignaste mentores',
    'configuraste equipos',
    'diste accesos',
    'explicaste cultura',
    'compartiste valores',
    'alineaste expectativas',
    'estableciste metas',
    'definiste KPIs',
    'trackeaste progreso',
    'mediste impacto',
    'reportaste resultados',
    'celebraste wins',
    'compartiste éxitos',
    'agradeciste contribuciones',
    'reconociste esfuerzos extra',
    'premiaste excelencia',
    'incentivaste performance',
    'motivaste con propósito',
    'inspiraste con visión',
    'lideraste con ejemplo',
    'demostraste valores',
    'actuaste consistentemente',
    'mantuviste palabra',
    'cumpliste compromisos',
    'fuiste confiable',
    'estuviste disponible',
    'respondiste rápido',
    'fuiste accesible',
    'mantuviste puertas abiertas',
    'escuchaste activamente',
    'mostraste empatía',
    'entendiste perspectivas',
    'consideraste contextos',
    'fuiste compasivo',
    'apoyaste en momentos difíciles',
    'mostraste flexibilidad',
    'adaptaste approach',
    'personalizaste ayuda',
    'diste espacio cuando fue necesario',
    'respetaste límites',
    'mantuviste balance',
    'promoviste bienestar',
    'cuidaste salud mental',
    'preveniste burnout',
    'identificaste señales',
    'interveniste a tiempo',
    'ofreciste recursos',
    'conectaste con ayuda profesional',
    'normalizaste conversaciones de salud',
    'removiste estigmas',
    'creaste ambiente seguro',
    'promoviste vulnerabilidad',
    'compartiste tu humanidad',
    'admitiste no saber',
    'pediste ayuda cuando la necesitaste',
    'mostraste que está bien fallar',
    'celebraste intentos',
    'recompensaste riesgos',
    'promoviste experimentación',
    'permitiste fallar rápido',
    'aprendiste de errores',
    'compartiste lecciones',
    'creaste cultura de aprendizaje',
    'invertiste en desarrollo',
    'financiaste capacitación',
    'apoyaste conferencias',
    'promoviste certificaciones',
    'valoraste crecimiento',
    'creaste planes de carrera',
    'tuviste conversaciones de desarrollo',
    'identificaste aspiraciones',
    'alineaste intereses con necesidades',
    'creaste oportunidades',
    'delegaste responsabilidades',
    'confiaste en capacidades',
    'empoderaste para decidir',
    'diste autonomía',
    'removiste micromanagement',
    'enfocaste en outcomes',
    'valoraste resultados sobre horas',
    'mediste impacto real',
    'promoviste productividad sostenible',
    'respetaste tiempo personal',
    'desalentaste overtime',
    'promoviste descanso',
    'respetaste vacaciones',
    'desconectaste fuera de horario',
    'modelaste balance',
    'priorizaste salud',
    'promoviste ejercicio',
    'incentivaste alimentación saludable',
    'facilitaste pausas',
    'creaste espacios de descanso',
    'promoviste socialización',
    'organizaste actividades de equipo',
    'celebraste juntos',
    'creaste tradiciones',
    'construiste cultura única',
    'definiste identidad de equipo',
    'articulaste valores compartidos',
    'viviste principios',
    'mantuviste estándares',
    'no comprometiste calidad',
    'perseguiste excelencia',
    'refinaste continuamente',
    'puliste detalles',
    'perfeccionaste craft',
    'desarrollaste expertise',
    'profundizaste conocimiento',
    'te especializaste',
    'dominaste tu campo',
    'te convertiste en referente',
    'compartiste expertise',
    'enseñaste a otros',
    'elevaste el nivel',
    'subiste el estándar',
    'inspiraste a mejorar',
    'contagiaste pasión',
    'mostraste entusiasmo',
    'mantuviste energía',
    'irradiaste positividad',
    'levantaste ánimos',
    'mantuviste optimismo',
    'viste oportunidades',
    'enfocaste en soluciones',
    'mantuviste perspectiva',
    'recordaste el por qué',
    'conectaste con propósito',
    'encontraste significado',
    'valoraste impacto',
    'mediste diferencia',
    'contribuiste positivamente',
    'dejaste huella',
    'creaste legado',
    'construiste algo duradero',
    'plantaste semillas',
    'invertiste en futuro',
    'pensaste a largo plazo',
    'tomaste decisiones sostenibles',
    'priorizaste impacto',
    'maximizaste valor',
    'optimizaste para el bien común',
    'balanceaste intereses',
    'consideraste todos los stakeholders',
    'actuaste responsablemente',
    'fuiste buen ciudadano corporativo',
    'respetaste el medio ambiente',
    'minimizaste desperdicios',
    'reciclaste recursos',
    'reutilizaste cuando pudiste',
    'redujiste consumo',
    'promoviste sustentabilidad',
    'educaste sobre impacto',
    'lideraste con propósito',
    'alineaste profit con purpose',
    'creaste impacto positivo',
    'contribuiste a sociedad',
    'retribuiste a comunidad',
    'apoyaste causas',
    'donaste tiempo',
    'compartiste recursos',
    'usaste privilegio para bien',
    'amplificaste voces marginadas',
    'creaste oportunidades equitativas',
    'removiste barreras',
    'democratizaste acceso',
    'nivelaste el campo de juego',
    'luchaste por justicia',
    'defendiste derechos',
    'alzaste voz por otros',
    'fuiste aliado',
    'mostraste solidaridad',
    'actuaste con valentía',
    'tomaste posición',
    'hiciste lo correcto',
    'mantuviste brújula moral',
    'guiaste con valores',
    'inspiraste a otros a ser mejores',
    'elevaste a quienes te rodeaban',
    'creaste efecto multiplicador',
    'generaste impacto en cadena',
    'tocaste vidas',
    'hiciste diferencia',
    'importaste',
    'agregaste valor único',
    'fuiste insustituible',
    'dejaste mejor las cosas',
    'plantaste árboles bajo cuya sombra nunca te sentarás',
    'construiste para generaciones futuras',
    'pensaste en legado',
    'trascendiste',
    'impactaste profundamente',
    'cambiaste vidas',
    'creaste oportunidades',
    'abriste puertas',
    'iluminaste caminos',
    'guiaste en oscuridad',
    'diste esperanza',
    'inspiraste posibilidad',
    'mostraste que se puede',
    'rompiste techos de cristal',
    'desafiaste límites',
    'expandiste horizontes',
    'reimaginaste posibilidades',
    'soñaste en grande',
    'perseguiste visiones',
    'materializaste ideas',
    'convertiste sueños en realidad',
    'hiciste lo imposible posible',
    'superaste expectativas',
    'excediste estándares',
    'sorprendiste positivamente',
    'deleitaste clientes',
    'creaste fans',
    'generaste lealtad',
    'construiste marca personal',
    'cultivaste reputación',
    'ganaste respeto',
    'te convertiste en referencia',
    'estableciste autoridad',
    'demostraste expertise',
    'ganaste confianza',
    'construiste credibilidad',
    'mantuviste consistencia',
    'cumpliste promesas',
    'sobre-entregaste',
    'sorprendiste gratamente',
    'excediste lo esperado',
    'agregaste ese extra',
    'fuiste más allá',
    'hiciste milla extra',
    'diste 110%',
    'no te conformaste',
    'perseguiste excelencia',
    'nunca te detuviste',
    'seguiste mejorando',
    'evolucionaste constantemente',
    'creciste continuamente',
    'te transformaste',
    'te reinventaste',
    'te adaptaste',
    'pivoteaste cuando fue necesario',
    'fluiste con cambios',
    'abrazaste incertidumbre',
    'encontraste oportunidad en crisis',
    'convertiste limones en limonada',
    'hiciste de necesidad virtud',
    'transformaste desafíos en ventajas',
    'usaste obstáculos como trampolines',
    'rebotaste de fracasos',
    'te levantaste cada vez',
    'mostraste resiliencia',
    'demostraste grit',
    'perseveraste',
    'no te rendiste',
    'seguiste adelante',
    'mantuviste rumbo',
    'confiaste en proceso',
    'tuviste paciencia',
    'jugaste largo plazo',
    'plantaste semillas hoy',
    'cosecharás mañana',
    'invertiste en ti mismo',
    'apostaste por tu crecimiento',
    'priorizaste desarrollo',
    'nunca dejaste de aprender',
    'mantuviste curiosidad',
    'hiciste preguntas',
    'cuestionaste todo',
    'buscaste entender',
    'profundizaste',
    'no te quedaste en superficie',
    'excavaste más profundo',
    'encontraste verdad',
    'llegaste a esencia',
    'comprendiste realmente',
    'conectaste puntos',
    'viste patrones',
    'sintetizaste complejidad',
    'simplificaste sin perder profundidad',
    'comunicaste claramente',
    'explicaste de forma simple',
    'hiciste accesible lo complejo',
    'democratizaste conocimiento',
    'compartiste sabiduría',
    'enseñaste generosamente',
    'mentoreaste con paciencia',
    'guiaste con amor',
    'serviste con humildad',
    'lideraste desde atrás',
    'empoderaste a otros',
    'hiciste brillar a tu equipo',
    'celebraste logros ajenos',
    'te alegraste por éxitos de otros',
    'no tuviste envidia',
    'colaboraste en lugar de competir',
    'sumaste en vez de restar',
    'construiste puentes',
    'uniste en vez de dividir',
    'encontraste puntos en común',
    'enfocaste en similitudes',
    'respetaste diferencias',
    'celebraste diversidad',
    'aprendiste de perspectivas diferentes',
    'expandiste tu mente',
    'creciste como persona',
    'te convertiste en mejor versión',
    'evolucionaste conscientemente',
    'trabajaste en ti mismo',
    'sanaste heridas',
    'soltaste resentimientos',
    'perdonaste',
    'liberaste',
    'te renovaste',
    'renaciste',
    'comenzaste de nuevo',
    'tomaste segunda oportunidad',
    'aprovechaste chance',
    'no desperdiciaste momento',
    'viviste plenamente',
    'estuviste presente',
    'disfrutaste el viaje',
    'apreciaste proceso',
    'encontraste alegría en el hacer',
    'amaste tu trabajo',
    'encontraste vocación',
    'descubriste propósito',
    'alineaste pasión con profesión',
    'hiciste de hobby tu carrera',
    'monetizaste tu talento',
    'creaste valor de tus dones',
    'compartiste tus regalos',
    'usaste talentos para servir',
    'pusiste skills al servicio de otros',
    'contribuiste desde tu fortaleza',
    'maximizaste tu impacto único',
    'hiciste lo que solo tú puedes hacer',
    'fuiste auténtico',
    'mostraste tu verdad',
    'te quitaste máscaras',
    'fuiste vulnerable',
    'compartiste tu historia',
    'inspiraste con tu ejemplo',
    'demostraste que es posible',
    'rompiste mitos',
    'desafiaste narrativas',
    'reescribiste guiones',
    'creaste nuevas posibilidades',
    'expandiste lo imaginable',
    'soñaste lo imposible',
    'perseguiste lo inalcanzable',
    'alcanzaste lo improbable',
    'lograste lo extraordinario',
    'hiciste magia',
    'creaste milagros cotidianos',
    'transformaste lo ordinario en extraordinario',
    'encontraste belleza en lo simple',
    'apreciaste pequeñas cosas',
    'valoraste detalles',
    'notaste lo que otros ignoran',
    'viste oportunidades donde otros ven problemas',
    'encontraste luz en oscuridad',
    'mantuviste esperanza',
    'creyste cuando otros dudaron',
    'confiaste cuando parecía imposible',
    'tuviste fe en proceso',
    'supiste que llegarías',
    'mantuviste convicción',
    'no te dejaste desanimar',
    'bloqueaste negatividad',
    'protegiste tu energía',
    'mantuviste vibración alta',
    'irradiaste luz',
    'contagiaste entusiasmo',
    'elevaste frecuencia',
    'creaste campo positivo',
    'influenciaste ambiente',
    'cambiaste atmósfera',
    'transformaste espacios',
    'mejoraste lugares',
    'dejaste sitios mejor que como los encontraste',
    'limpiaste lo que ensuciaron otros',
    'reparaste lo que rompieron otros',
    'sanaste lo que dañaron otros',
    'construiste sobre ruinas',
    'creaste belleza de cenizas',
    'transformaste dolor en arte',
    'convertiste heridas en sabiduría',
    'hiciste de cicatrices mapas',
    'usaste pasado como maestro',
    'aprendiste de experiencias',
    'no repetiste errores',
    'evolucionaste de errores',
    'creciste de desafíos',
    'te fortaleciste en adversidad',
    'te templaste en fuego',
    'saliste más fuerte',
    'emergiste transformado',
    'renaciste de crisis',
    'te encontraste en pérdida',
    'descubriste fortaleza en vulnerabilidad',
    'hallaste poder en rendición',
    'ganaste soltando',
    'avanzaste retrocediendo',
    'creciste encogiéndote',
    'te expandiste contrayéndote',
    'encontraste plenitud en vacío',
    'hallaste abundancia en simplicidad',
    'descubriste riqueza en pobreza',
    'viste bendición en maldición',
    'transformaste perspectiva',
    'cambiaste lente',
    'viste con nuevos ojos',
    'escuchaste con nuevo corazón',
    'sentiste con nueva alma',
    'viviste con nueva consciencia',
    'despertaste',
    'te iluminaste',
    'te liberaste',
    'trascendiste',
    'te elevaste',
    'ascendiste',
    'evolucionaste',
    'te transformaste',
    'te convertiste',
    'llegaste a ser',
    'realizaste potencial',
    'manifestaste destino',
    'cumpliste propósito',
    'completaste misión',
    'honraste llamado',
    'respondiste a vocación',
    'seguiste tu estrella',
    'alcanzaste tu norte',
    'llegaste a tu destino',
    'encontraste tu lugar',
    'descubriste tu porqué',
    'viviste tu verdad',
    'encarnaste tus valores',
    'alineaste palabras con acciones',
    'viviste con integridad',
    'mantuviste coherencia',
    'fuiste congruente',
    'caminaste tu hablar',
    'practicaste lo que predicaste',
    'demostraste con ejemplo',
    'lideraste desde el frente',
    'no pediste lo que no dabas',
    'diste más de lo que pedías',
    'serviste más de lo que tomabas',
    'agregaste más de lo que extraías',
    'contribuiste más de lo que consumías',
    'plantaste más de lo que cosechabas',
    'sembraste para futuro',
    'construiste para mañana',
    'creaste para posteridad',
    'legaste para siguientes',
    'dejaste herencia',
    'estableciste fundamento',
    'pusiste primera piedra',
    'iniciaste movimiento',
    'comenzaste revolución',
    'encendiste chispa',
    'prendiste fuego',
    'iluminaste oscuridad',
    'abriste camino',
    'marcaste ruta',
    'fuiste pionero',
    'exploraste lo desconocido',
    'aventuraste en lo incierto',
    'te arriesgaste a lo nuevo',
    'probaste lo no probado',
    'hiciste lo no hecho',
    'dijiste lo no dicho',
    'pensaste lo no pensado',
    'imaginaste lo inimaginable',
    'creaste lo increíble',
    'lograste lo impensable',
    'hiciste historia',
    'cambiaste el juego',
    'redefiniste reglas',
    'rompiste moldes',
    'saliste de caja',
    'pensaste diferente',
    'innovaste radicalmente',
    'revolucionaste campo',
    'transformaste industria',
    'impactaste mundo',
    'cambiaste paradigma',
    'alteraste curso',
    'influyeste destino',
    'moldeaste futuro',
    'creaste mañana',
    'construiste lo que viene',
    'diseñaste porvenir',
    'imaginaste lo posible',
    'hiciste real lo soñado',
    'manifestaste visión',
    'materializaste intención',
    'concretaste propósito',
    'realizaste plan',
    'ejecutaste estrategia',
    'implementaste solución',
    'resolviste problema',
    'encontraste respuesta',
    'descubriste verdad',
    'alcanzaste comprensión',
    'llegaste a sabiduría',
    'obtuviste maestría',
    'lograste excelencia',
    'alcanzaste grandeza',
    'tocaste gloria',
    'saboreaste victoria',
    'experimentaste triunfo',
    'celebraste logro',
    'disfrutaste éxito',
    'compartiste abundancia',
    'distribuiste riqueza',
    'esparciste prosperidad',
    'multiplicaste bendiciones',
    'amplificaste bien',
    'maximizaste positivo',
    'optimizaste beneficio',
    'incrementaste valor',
    'aumentaste impacto',
    'expandiste influencia',
    'extendiste alcance',
    'ampliaste círculo',
    'creciste comunidad',
    'construiste tribu',
    'formaste familia',
    'creaste hogar',
    'estableciste santuario',
    'construiste refugio',
    'creaste espacio seguro',
    'abriste puertas',
    'diste bienvenida',
    'acogiste',
    'abrazaste',
    'incluiste',
    'integraste',
    'uniste',
    'conectaste',
    'enlazaste',
    'vinculaste',
    'relacionaste',
    'asociaste',
    'aliaste',
    'coaligaste',
    'confederaste',
    'fusionaste',
    'amalgamaste',
    'integraste',
    'sintetizaste',
    'armonizaste',
    'balanceaste',
    'equilibraste',
    'centraste',
    'enfocaste',
    'concentraste',
    'dirigiste',
    'orientaste',
    'guiaste',
    'condujiste',
    'lideraste',
    'capitaneaste',
    'piloteaste',
    'navegaste',
    'timoneaste',
    'gobernaste',
    'administraste',
    'gestionaste',
    'manejaste',
    'operaste',
    'ejecutaste',
    'llevaste a cabo',
    'realizaste',
    'efectuaste',
    'concretaste',
    'culminaste',
    'completaste',
    'finalizaste',
    'terminaste',
    'concluyiste',
    'cerraste',
    'sellaste',
    'aseguraste',
    'garantizaste',
    'confirmaste',
    'validaste',
    'verificaste',
    'comprobaste',
    'certificaste',
    'atestiguaste',
    'testimoniaste',
    'evidenciaste',
    'demostraste',
    'probaste',
    'justificaste',
    'fundamentaste',
    'sustentaste',
    'apoyaste',
    'respaldaste',
    'reforzaste',
    'fortaleciste',
    'consolidaste',
    'afianzaste',
    'aseguraste',
    'estabilizaste',
    'solidificaste',
    'cristalizaste',
    'materializaste visión',
    'hiciste tangible lo abstracto',
    'convertiste ideas en realidad',
    'bajaste conceptos a tierra',
    'aterrizaste propuestas',
    'implementaste teorías',
    'aplicaste conocimiento',
    'pusiste en práctica',
    'ejerciste habilidades',
    'demostraste capacidades',
    'exhibiste talentos',
    'mostraste destrezas',
    'revelaste potencial',
    'desplegaste arsenal',
    'activaste recursos',
    'movilizaste activos',
    'aprovechaste oportunidades',
    'capitalizaste momentos',
    'explotaste ventanas',
    'aprovechaste coyunturas',
    'usaste circunstancias',
    'navegaste contextos',
    'adaptaste a situaciones',
    'ajustaste a realidades',
    'moldeaste a necesidades',
    'respondiste a demandas',
    'atendiste requerimientos',
    'satisficiste necesidades',
    'cumpliste expectativas',
    'llenaste vacíos',
    'cubriste huecos',
    'parchaste agujeros',
    'sellaste grietas',
    'reparaste fracturas',
    'sanaste rupturas',
    'remendaste desgarros',
    'zurciste tejidos',
    'cosiste heridas',
    'curaste dolencias',
    'aliviaste sufrimientos',
    'mitigaste dolores',
    'redujiste malestares',
    'calmaste angustias',
    'tranquilizaste ansiedades',
    'apaciguaste temores',
    'disipaste miedos',
    'desterraste terrores',
    'venciste fobias',
    'superaste traumas',
    'trascendiste limitaciones',
    'rompiste cadenas',
    'quebraste grilletes',
    'liberaste ataduras',
    'soltaste amarres',
    'cortaste cuerdas',
    'rompiste lazos tóxicos',
    'te desataste de lo dañino',
    'te desprendiste de lo negativo',
    'te liberaste de cargas',
    'soltaste pesos',
    'dejaste lastres',
    'abandonaste equipajes',
    'desprendiste mochilas',
    'vaciaste bultos',
    'aligeraste carga',
    'redujiste peso',
    'minimizaste fardo',
    'simplificaste equipaje',
    'streamlineaste procesos',
    'optimizaste flujos',
    'mejoraste sistemas',
    'perfeccionaste métodos',
    'refinaste técnicas',
    'puliste procedimientos',
    'suavizaste operaciones',
    'fluidificaste gestiones',
    'agilizaste trámites',
    'aceleraste procesos',
    'dinamizaste operativas',
    'vivificaste estructuras',
    'energizaste organizaciones',
    'revitalizaste empresas',
    'rejuveneciste instituciones',
    'renovaste corporaciones',
    'modernizaste compañías',
    'actualizaste negocios',
    'digitalizaste operaciones',
    'automatizaste tareas',
    'robotizaste funciones',
    'informatizaste gestiones',
    'sistematizaste procesos',
    'estandarizaste procedimientos',
    'normalizaste operaciones',
    'regularizaste funciones',
    'uniformizaste métodos',
    'homogeneizaste técnicas',
    'igualaste estándares',
    'nivelaste calidades',
    'equiparaste niveles',
    'balanceaste proporciones',
    'proporcionaste equilibrios',
    'armonizaste relaciones',
    'sincronizaste ritmos',
    'coordinaste tiempos',
    'alineaste plazos',
    'ajustaste cronogramas',
    'calibraste agendas',
    'templaste calendarios',
    'afinaste programaciones',
    'precisaste timing',
    'exactaste momentos',
    'puntualizaste instantes',
    'especificaste tiempos',
    'determinaste fechas',
    'estableciste hitos',
    'fijaste mojones',
    'marcaste referencias',
    'señalaste indicadores',
    'apuntaste métricas',
    'registraste medidas',
    'anotaste datos',
    'documentaste información',
    'archivaste registros',
    'almacenaste documentos',
    'guardaste respaldos',
    'preservaste copias',
    'conservaste originales',
    'mantuviste integridad',
    'protegiste autenticidad',
    'custodiaste veracidad',
    'salvaguardaste legitimidad',
    'resguardaste validez',
    'defendiste legalidad',
    'amparaste licitud',
    'protegiste juridicidad',
    'blindaste conformidad',
    'aseguraste compliance',
    'garantizaste cumplimiento',
    'certificaste adherencia',
    'acreditaste observancia',
    'avalaste seguimiento',
    'respaldaste acatamiento',
    'corroboraste obediencia',
    'sustentaste respeto',
    'fundamentaste consideración',
    'basaste en principios',
    'cimentaste en valores',
    'enraizaste en ética',
    'ancoraste en moral',
    'afirmaste en rectitud',
    'apoyaste en integridad',
    'sostuviste con honestidad',
    'mantuviste con probidad',
    'preservaste dignidad',
    'guardaste honor',
    'conservaste reputación',
    'cuidaste prestigio',
    'velaste por imagen',
    'protegiste nombre',
    'defendiste marca',
    'amparaste identidad',
    'resguardaste esencia',
    'salvaguardaste core',
    'custodiaste centro',
    'blindaste núcleo',
    'fortificaste corazón',
    'reforzaste médula',
    'consolidaste sustancia',
    'compactaste materia',
    'densificaste contenido',
    'concentraste esencia',
    'destilaste pureza',
    'refinaste calidad',
    'sublimaste excelencia',
    'elevaste estándar',
    'alzaste nivel',
    'subiste vara',
    'levantaste barra',
    'aumentaste exigencia',
    'incrementaste rigor',
    'intensificaste rigurosidad',
    'profundizaste meticulosidad',
    'ahondaste minuciosidad',
    'cavaste profundidad',
    'excavaste hondura',
    'perforaste superficie',
    'penetraste corteza',
    'traspasaste capa',
    'atravesaste velo',
    'superaste umbral',
    'rebasaste límite',
    'excediste frontera',
    'sobrepasaste lindero',
    'trascendiste confín',
    'desbordaste margen',
    'derramaste copa',
    'rebosaste recipiente',
    'colmaste medida',
    'llenaste hasta el borde',
    'completaste hasta tope',
    'saciaste apetito',
    'satisficiste hambre',
    'calmaste sed',
    'aplacaste ansia',
    'aquietaste anhelo',
    'sosegaste deseo',
    'serenaste voluntad',
    'pacificaste intención',
    'tranquilizaste aspiración',
    'apaciguaste ambición',
    'moderaste pretensión',
    'templaste afán',
    'conteniste ímpetu',
    'controlaste impulso',
    'dominaste urgencia',
    'gobernaste premura',
    'registe apresuramiento',
    'dirigiste precipitación',
    'encauzaste apuro',
    'canalizaste prisa',
    'orientaste velocidad',
    'guiaste rapidez',
    'condujiste celeridad',
    'piloteaste presteza',
    'timoneaste prontitud',
    'capitaneaste diligencia',
    'lideraste eficiencia',
    'coordinaste efectividad',
    'organizaste productividad',
    'estructuraste rendimiento',
    'sistematizaste desempeño',
    'ordenaste performance',
    'clasificaste resultados',
    'categorizaste outcomes',
    'jerarquizaste logros',
    'priorizaste éxitos',
    'rankeaste victorias',
    'ordenaste triunfos',
    'listaste conquistas',
    'enumeraste hazañas',
    'detallaste proezas',
    'especificaste glorias',
    'pormenorizaste lauros',
    'describiste honores',
    'narraste distinciones',
    'relataste reconocimientos',
    'contaste premios',
    'referiste galardones',
    'mencionaste condecoraciones',
    'citaste medallones',
    'nombraste trofeos',
    'indicaste placas',
    'señalaste certificados',
    'apuntaste diplomas',
    'registraste títulos',
    'anotaste grados',
    'documentaste credenciales',
    'archivaste cualificaciones',
    'almacenaste competencias',
    'guardaste habilidades',
    'preservaste destrezas',
    'conservaste pericias',
    'mantuviste maestrías',
    'protegiste expertise',
    'custodiaste know-how',
    'salvaguardaste savoir-faire',
    'resguardaste capacidades',
    'defendiste aptitudes',
    'amparaste facultades',
    'blindaste potencias',
    'fortificaste poderes',
    'reforzaste fuerzas',
    'consolidaste energías',
    'compactaste vigor',
    'densificaste potencial',
    'concentraste capacidad',
    'destilaste habilidad',
    'refinaste destreza',
    'sublimaste talento',
    'elevaste genio',
    'alzaste ingenio',
    'subiste creatividad',
    'levantaste innovación',
    'aumentaste invención',
    'incrementaste originalidad',
    'intensificaste unicidad',
    'profundizaste singularidad',
    'ahondaste particularidad',
    'cavaste especificidad',
    'excavaste individualidad',
    'perforaste personalidad',
    'penetraste carácter',
    'traspasaste temperamento',
    'atravesaste naturaleza',
    'superaste esencia íntima',
    'rebasaste ser profundo',
    'excediste yo interior',
    'sobrepasaste alma interna',
    'trascendiste espíritu íntimo',
    'desbordaste consciencia',
    'derramaste awareness',
    'rebosaste presencia',
    'colmaste mindfulness',
    'llenaste atención plena',
    'completaste enfoque total',
    'saciaste concentración absoluta',
    'satisficiste absorción completa',
    'calmaste inmersión total',
    'aplacaste flow state',
    'aquietaste zona de peak',
    'sosegaste estado óptimo',
    'serenaste rendimiento máximo',
    'pacificaste performance cumbre',
    'apaciguaste expresión suprema',
    'moderaste manifestación perfecta',
    'templaste realización ideal',
    'conteniste actualización plena',
    'controlaste potenciación máxima',
    'dominaste optimización total',
    'gobernaste maximización completa',
    'registe perfeccionamiento absoluto',
    'dirigiste refinamiento extremo',
    'encauzaste pulimiento total',
    'canalizaste acabado perfecto',
    'orientaste terminación impecable',
    'guiaste finalización exquisita',
    'condujiste conclusión magistral',
    'piloteaste cierre brillante',
    'timoneaste remate espléndido',
    'capitaneaste culminación magnífica',
    'lideraste consumación extraordinaria',
    'coordinaste realización prodigiosa',
    'organizaste concreción fenomenal',
    'estructuraste materialización asombrosa',
    'sistematizaste manifestación increíble',
    'ordenaste aparición sorprendente',
    'clasificaste emergencia notable',
    'categorizaste surgimiento memorable',
    'jerarquizaste nacimiento histórico',
    'priorizaste génesis trascendental',
    'rankeaste origen legendario',
    'ordenaste principio mítico',
    'listaste comienzo épico',
    'enumeraste inicio heroico',
    'detallaste arranque titánico',
    'especificaste partida olímpica',
    'pormenorizaste salida celestial',
    'describiste despegue divino',
    'narraste lanzamiento supremo',
    'relataste inauguración excelsa',
    'contaste apertura sublime',
    'referiste estreno glorioso',
    'mencionaste debut triunfal',
    'citaste presentación victoriosa',
    'nombraste introducción exitosa',
    'indicaste exhibición próspera',
    'señalaste demostración afortunada',
    'apuntaste muestra venturosa',
    'registraste exposición dichosa',
    'anotaste manifestación feliz',
    'documentaste revelación alegre',
    'archivaste divulgación gozosa',
    'almacenaste publicación jubilosa',
    'guardaste difusión radiante',
    'preservaste propagación luminosa',
    'conservaste expansión brillante',
    'mantuviste crecimiento resplandeciente',
    'protegiste desarrollo fulgurante',
    'custodiaste evolución deslumbrante',
    'salvaguardaste progreso radiante',
    'resguardaste avance luminoso',
    'defendiste adelanto brillante',
    'amparaste mejora espléndida',
    'blindaste perfeccionamiento magnífico',
    'fortificaste optimización gloriosa',
    'reforzaste potenciación majestuosa',
    'consolidaste maximización augusta',
    'compactaste intensificación noble',
    'densificaste amplificación ilustre',
    'concentraste magnificación eminente',
    'destilaste engrandecimiento distinguido',
    'refinaste exaltación señorial',
    'sublimaste enaltecimiento superior',
    'elevaste elevación suprema',
    'alzaste ascensión máxima',
    'subiste escalada cumbre',
    'levantaste subida pináculo',
    'aumentaste elevación cenit',
    'incrementaste ascenso apogeo',
    'intensificaste escalamiento ápice',
    'profundizaste promoción cúspide',
    'ahondaste progresión vértice',
    'cavaste mejoramiento altura',
    'excavaste avance altitud',
    'perforaste adelanto elevación',
    'penetraste desarrollo alzamiento',
    'traspasaste crecimiento encumbramiento',
    'atravesaste expansión ensalzamiento',
    'superaste evolución engrandecimiento',
    'rebasaste transformación enaltecimiento',
    'excediste metamorfosis glorificación',
    'sobrepasaste cambio magnificación',
    'trascendiste mutación sublimación',
    'desbordaste alteración elevación',
    'derramaste modificación exaltación',
    'rebosaste variación enaltecimiento',
    'colmaste innovación dignificación',
    'llenaste renovación honramiento',
    'completaste actualización celebración',
    'saciaste modernización consagración',
    'satisficiste rejuvenecimiento beatificación',
    'calmaste revitalización santificación',
    'aplacaste regeneración divinización',
    'aquietaste restauración deificación',
    'sosegaste rehabilitación apotheosis',
    'serenaste recuperación transfiguración',
    'pacificaste restablecimiento traslación',
    'apaciguaste reanimación transmutación',
    'moderaste resurrección transustanciación',
    'templaste renacimiento metempsicosis',
    'conteniste palingenesia reencarnación',
    'controlaste redención redención final',
    'dominaste salvación salvación eterna',
    'gobernaste liberación liberación total',
    'registe emancipación emancipación completa',
    'dirigiste manumisión manumisión absoluta',
    'encauzaste exoneración exoneración definitiva',
    'canalizaste absolución absolución perfecta',
    'orientaste perdón perdón infinito',
    'guiaste gracia gracia divina',
    'condujiste misericordia misericordia celestial',
    'piloteaste clemencia clemencia suprema',
    'timoneaste piedad piedad infinita',
    'capitaneaste compasión compasión eterna',
    'lideraste caridad caridad perfecta',
    'coordinaste amor amor incondicional',
    'organizaste bondad bondad absoluta',
    'estructuraste generosidad generosidad infinita',
    'sistematizaste magnanimidad magnanimidad suprema',
    'ordenaste largueza largueza divina',
    'clasificaste munificencia munificencia celestial',
    'categorizaste liberalidad liberalidad perfecta',
    'jerarquizaste desprendimiento desprendimiento total',
    'priorizaste altruismo altruismo puro',
    'rankeaste filantropía filantropía sublime',
    'ordenaste humanitarismo humanitarismo noble',
    'listaste benevolencia benevolencia excelsa',
    'enumeraste beneficencia beneficencia augusta',
    'detallaste benignidad benignidad majestuosa'
];

export default {
    commands: ['work', 'w'],
    async execute(ctx) {
        if (ctx.isGroup && !ctx.dbService.getGroup(ctx.chatId).settings.economy) {
            return await ctx.reply(styleText('ꕤ El sistema de economía está desactivado en este grupo.'));
        }
        const COOLDOWN = 1 * 60 * 1000;
        const REWARD = Math.floor(Math.random() * (3000 - 1000 + 1)) + 1000;
        const userData = ctx.userData;
        const cooldown = getCooldown(userData.economy.lastWork, COOLDOWN);
        if (cooldown > 0) {
            return await ctx.reply(styleText(
                `ꕤ Estás cansado, descansa un poco.\n> Vuelve en » ${formatTime(cooldown)}`
            ));
        }
        ctx.dbService.updateUser(ctx.sender, {
            'economy.lastWork': Date.now(),
            'economy.coins': userData.economy.coins + REWARD
        });
        const job = getRandom(JOBS);
        await ctx.reply(styleText(
            `ꕥ ${job} y ganaste *¥${formatNumber(REWARD)}* coins.`
        ));
    }
};